---
Description: This rule file defines the basic project structure
glob: folders
---

# Multi Module Project Structure

## intelligent_test_generator
**Purpose**: generate test cases in csv format from the PRD input  
**Root Folder Name**: intelligent_test_generator

**Project Structure**
- the project should use a standard python framework structure
- configuration file should be under resources following python standard project

**Feature**
- The module should be able to compile and run in isolation
- The module is responsible for generating test plan from the PRD

**Inputs**
- program reads the configuration defining the PRD 
- program reads and analyse the PRD

## Intelligent test case reviewer

**Purpose**: review test cases generated by intelligent_test_generator and provide feedback in structured output format
**Root Folder Name**: intelligent_test_reviewer

**Project Structure**  
- the project should use a standard python framework structure
- configuration file should be under resources following python standard project

**Feature**
- The module should be able to compile and run in isolation
- The module is responsible for generating test plan from the PRD

**Inputs**
- program reads the configuration defining the PRD 
- program reads and analyse the PRD
and analyse the test cases generated from Intelligent_test_generator and provide feedbacks in structured output format

## Intelligent Common Module

**Purpose**: Repository of common utilities for all other modules
**Root Folder Name**: intelligent_common_utils
 
**Tech Stack**
- Python
- LangChain
- LangGraph
- Postgres
- LangSmith
- TypeDict
- Annotated reducer
- Pydantic for Structured output
- FastAPI wrapper for jenkins integration

Concrete language, library, and database versions for this tech stack are defined in `[.cursor/rules/TECH_STACK_VERSIONS.md](.cursor/rules/TECH_STACK_VERSIONS.md)`. Keep project dependencies aligned with that rule file.

``` Follow standard project structure for Python with Docker 
my-agent-app/
├── src/
│   └── agent_core/
│       ├── __init__.py
│       ├── main.py          # Entry point
│       ├── agent.py         # Agent logic/planning
│       ├── tools/           # Custom tool definitions
│       │   ├── __init__.py
│       │   └── search.py
│       └── utils/           # Shared utilities
├── tests/
├── config/                  # Configuration files
├── k8s/                     # Kubernetes manifests
│   ├── deployment.yaml
│   └── service.yaml
├── Dockerfile               # Multi-stage Docker build
├── requirements.txt
└── README.md
```